language: java

jdk:
  - oraclejdk8

after_success:
  - test "${TRAVIS_JDK_VERSION}" == "oraclejdk8" && mvn javadoc:jar
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./travis/publish_to_bintray.sh

branches:
  only:
    - master
    - /^(?i:sshd_proxy)-.*$/

env:
  global:
  - secure: KVFZIMNqNr6IgGQFfUItvEwLoKoDiMLZPWrHs3DNWGgXXYTCNQdeETQmcZ6H6dy8fypPk2YKJnyNc5Vwnt9m8F19A6aR3cQL0d86zrGGyrayUvVVlYcpdKpVRgHqpOj6L+fi8amZhNIKG7Nnn5MqfjkBx89I8yo5HLuMNh4XM7A=
  - secure: Lf4CIwsDhltD9d48c/qMt8UHB7UrA2x7RatyD99t6LgfQKyBtHz2V2+DbbB7RewnJDV8C4hUNK21qIj6MOrDJM0cW9iUXlSJypdV8TjN0/NHHURkFVhpxK2cFghArVysmbWq05lRgkTjwniCI+hlLdpNdx6D/KfRgegvWI8mBNs=
